---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: build-dev

  # Build again, this time with the newly 'just-built' image, as a test
- name: test
  pull: never
  image: build-dev
  settings:
    repo: spritsail/docker-build

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/docker-build
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 08751e21c9d1116b8e3da54bffcfbe80edf3912e7749f3d7df92905baabafba0

...
