pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: build-dev

  # Build again, this time with the newly 'just-built' image, as a test
  test:
    image: build-dev
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: spritsail/docker-build

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    repo: spritsail/docker-build

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
